#!/usr/bin/env node
'use strict';
const fs = require('fs');             function p(a,b,c){throw Error(a+' parser stopped here: "'+b.substring(c,c+100)+'"');};const q=new Set("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),r=/<!doctype[^>]*>|\x3c!--[\s\S]*?--\x3e|<script[^>]*>[\s\S]*?<\/script>|<style[^>]*>[\s\S]*?<\/style>|<link[^>]*>|<meta[^>]*>/gmi,t={s:/\s*<([\w-]+)\s*/myi,b:/\s*([\w-:]+)(?:="([^"]*)"|='([^']*)'|=([\w-]+))?\s*/myi,w:/\s*(\/?>)\s*/myi,A:/\s*[^<]*/my,l:/\s*<\/[\w-]+>\s*/myi};
function u(a){function b(l){d=l.lastIndex;for(let k in t)t[k].lastIndex=d}function c(){e=t.l.exec(a);if(null!=e)b(t.l),f.push(3);else if(e=t.s.exec(a),null!=e){b(t.s);let l=e[1];f.push(1,l);let k;for(;null!==(g=t.b.exec(a));)b(t.b),k=k||new Map,k.set(g[1],(g[2]||g[3]||g[4]||"").trim());k&&f.push(2,k);g=t.w.exec(a);(q.has(l)||"/>"==g[1])&&f.push(3);b(t.w)}else e=t.A.exec(a),null!=e&&b(t.A)}let d=0,e,g,f=[],h=d;for(;d<a.length;)c(),h===d&&p("html",a,d),h=d;b({lastIndex:0});return f}const v=new Set;
function w(a,b,c){return{tagName:b,attributes:c,classList:null!=c&&c.has("class")?new Set(c.get("class").split(/\s+/g)):v,parentNode:a,childNodes:[]}}const x=[];function y(a,b){if(null!=a){let c=a.C=a.C||{};if(!(b in c)){let d=0;c[b]=a.childNodes.filter(e=>{if(e.tagName==b)return e.g=d++,!0})}return c[b]}return x}
function z(a,b){let c=w(null,"root",v),d;for(let e=0;e<a.length;e++)switch(a[e]){case 1:{let g=a[++e],f=v;2===a[e+1]&&(e+=2,f=a[e]);d=c.childNodes.length;c.childNodes.push(c=w(c,g,f));b(c,d);break}case 3:c=c.parentNode}}function C(a,b,c){a.a=b;b=a.attributes;c.tag.add(a.tagName);a.classList.forEach(d=>c.B.add(d));b.has("id")&&c.h.add("[id="+b.get("id")+"]");b.has("type")&&c.h.add("[type="+b.get("type")+"]");c.i.push(a)}
function D(a){a=a.replace(r,"");a=u(a);const b={i:[],tag:new Set(["*"]),B:new Set,h:new Set};z(a,(c,d)=>C(c,d,b));return b};const E=/\s*\/\*[\s\S]*?\*\/\s*/gm,F=/\s*[>~+.#]\s*|\[[^\]]+\]|\s+/gm;function G(a){a=a.split(/\s*,\s*/gm);a.push(a.map(b=>I(b).trim().replace(F,(c,d)=>{c=c.trim();return 0==d?c:"."==c||"#"==c?"`"+c:1>=c.length?"`":"`"+c.replace(/['"]/gm,"")}).split(/`+/gm)));return a}const J=/:[a-z-]+\([^()]*\)/;function I(a){let b=a.length;for(;;){a=a.replace(J,"");if(a.length==b)break;b=a.length}return a.replace(/:?:[a-z-]+/gm,"")}
function K(a,b,c,d){let e="",g=1;for(;;){a[b]==c?g++:a[b]==d&&g--;if(0==g)break;e+=a[b++]}return e}
function L(a){function b(k){g=k.lastIndex;for(let m in d)d[m].lastIndex=g}function c(){if(0<e&&(f=d.j.exec(a),null!=f)){e--;h.push(2);b(d.j);return}f=d.u.exec(a);if(null!=f){let k=f[1];b(d.u);if("@"==k[0])switch(k.match(/@[a-z-]+/)[0]){case "@media":case "@supports":case "@document":e++;h.push(1,k);break;case "@import":case "@charset":case "@namespace":h.push(5,k+";");break;default:{e++;let m=K(a,g,"{","}");b({lastIndex:g+m.length});h.push(1,k,5,m)}}else h.push(3,G(f[1])),f=d.v.exec(a),h.push(4,f[1]),
b(d.v)}else g=a.length}const d={u:/\s*([^{;]+?)\s*[{;]\s*/my,v:/\s*([^}]*?)\s*\}/my,j:/\s*\}/my,D:/\s*([^{]*?)\{([^}]+?)\}/my};let e=0,g=0,f,h=[],l=g;for(;g<a.length;)c(),l===g&&p("css",a,g),l=g;return h}function M(a){a=a.replace(E,"");return L(a)}
function N(a,b){let c="",d=0;for(let e=0;e<a.length;e++)switch(a[e]){case 3:{let g=a[++e];d=g.length;0<d&&(g.forEach(f=>b.add(f)),c+=g.join());break}case 4:0<d&&(c+="{"+a[++e]+"}");break;case 1:c+=a[++e]+"{";break;case 2:c+="}";break;case 5:c+=a[++e]}return c.replace(/@[a-z-]+[^{]+\{\s*\}/gm,"")};function O(a,b,c){if(0>b&&0>=a)return!1;if(-1===a)return c<=b;if(0===a)return c===b;if(1===a)return 0>b||c>=b;let d=b%a;0>d&&(d+=a);return 1<a?c>=b&&c%a===d:c<=b&&c%(-1*a)===d};function P(a){function b(l){e=l.lastIndex;for(let k in d)d[k].lastIndex=e}function c(){let l=!1;if(f=d.m.exec(a)){l=!0;var k=f[0].trim();""==k&&(k=" ");g.push(k);b(d.m);h=g.length-1}else if(f=d.o.exec(a))if(l=!0,k=f[0].trim(),b(d.o),":"==k){f=d.c.exec(a);if("("==f[2]){let m=K(a,d.c.lastIndex,"(",")");d.c.lastIndex+=m.length+1;f[2]="not"==f[1]?P(m):m}g.splice(h+1,0,f[2],f[1],k);b(d.c)}else"["==k?(f=d.b.exec(a),g.splice(h+1,0,f[3],f[2],f[1],k),b(d.b)):(f=d.f.exec(a),g.push(f[1],k),b(d.f));else if(f=
d.f.exec(a))l=!0,g.push(f[1],"_"),b(d.f);return l}const d={f:/([\w*-]+)/iy,b:/([\w-]+)(?:(.?=)["']?([^\]]*?)["']?)?\]/iy,c:/([\w-]+)(\()?/iy,o:/\s*[:.#\[]\s*/iy,m:/\s*[>~+]\s*|\s+/iy};let e=0,g=[],f,h=-1;for(;e<a.length;)c();return g}const Q=/^([+-]?\d*)?n([+-]\d+)?$/;function R(a,b,c,d){d=d||"=";a=a.attributes;if(a.has(b))switch(b=a.get(b),d){case "=":return null==c||c==b;case "*=":return-1!=b.indexOf(c);case "^=":return b.startsWith(c);case "$=":return b.endsWith(c);case "~=":return c==b||b.startsWith(c+" ")||b.endsWith(" "+c)||-1!=b.indexOf(" "+c+" ")}return!1}
function S(a,b){if("odd"==b)a=1==a%2;else if("even"==b)a=0==a%2;else if(/^\d+$/.test(b))a=a==+b;else{var c=Q.exec(b);null!=c?(b=c[1],c=c[2],b=null==b||"+"==b?1:"-"==b?-1:+b,c=null==c?0:+c,b=[b,c]):b=[0,0];a=O(b[0],b[1],a)}return a}
function T(a,b){let c,d;for(;-1<b.a;){switch(a[b.a]){case "_":var e=a[--b.a];d=e==b.node.tagName||"*"==e;b.a--;break;case "#":var g=a[--b.a];d=R(b.node,"id",g,"=");b.a--;break;case ".":e=a[--b.a];d=b.node.classList.has(e);b.a--;break;case "[":e=a[--b.a];var f=a[--b.a];g=a[--b.a];d=R(b.node,e,g,f);b.a--;break;case ":":{e=a[--b.a];g=a[--b.a];let h=b.node,l=h.tagName;c=h.a;let k=(f=h.parentNode)?f.childNodes.length:1;switch(e){case "not":d=!T(g,{node:b.node,a:g.length-1});break;case "first-child":d=
0==c;break;case "last-child":d=c==k-1;break;case "only-child":d=1==k;break;case "nth-child":d=S(c+1,g);break;case "nth-last-child":d=S(k-c,g);break;case "first-of-type":y(f,l);d=0==h.g;break;case "last-of-type":e=y(f,l);d=h.g==e.length-1;break;case "only-of-type":e=y(f,l);d=1==e.length;break;case "nth-of-type":y(f,l);d=S(h.g+1,g);break;case "nth-last-of-type":e=y(f,l),d=S(e.length-h.g,g)}b.a--;break}case " ":c=--b.a;for(d=!1;!d;){f=b.node.parentNode;if(null==f)break;b.a=c;b.node=f;d=T(a,b)}break;
case ">":b.a--;f=b.node.parentNode;null!=f?(b.node=f,d=T(a,b)):d=!1;break;case "+":b.a--;f=b.node.parentNode;null!=f&&0<b.node.a?(b.node=f.childNodes[b.node.a-1],d=T(a,b)):d=!1;break;case "~":if(b.a--,d=!1,c=b.node.a,f=b.node.parentNode,null!=f&&0<c)for(g=0;g<c&&!d;g++)b.node=f.childNodes[g],d=T(a,b)}if(!d)break}return d}function U(a,b){return a.some(c=>T(b,{a:b.length-1,node:c}))};function V(a,b,c,d,e){e=e||"";for(let h=b.length-1;-1<h;h--){var g=b[h];if(!c.has(g[2])&&!0===d(e+g[2])){var f=g[0];g=g[1];a=a.slice(0,f)+""+a.slice(f+g)}}return a}const W=/([{};])\s*(--[\w-]+)\s*:\s*([^;}]+);?\s*/gm,X=/var\(([\w-]+)\)/gm,Y=/\s*,\s*/gm;function aa(a){let b={},c;for(;X.test(a);){for(;null!==(c=W.exec(a));)b[c[2]]=c[3];a=a.replace(X,(d,e)=>X.test(b[e])?d:b[e])}return a}
function ba(a,b,c){let d=[];var e=/@(?:-\w+-)?keyframes\s+([\w-]+)\s*\{/gm;let g;for(;null!==(g=e.exec(a));)d.push([g.index,g[0].length+K(a,e.lastIndex,"{","}").length+1,g[1]]);let f=new Set;for(e=/animation(?:-name)?:([^;!}]+)/gm;null!==(g=e.exec(b));)g[1].trim().split(Y).forEach(h=>{let l=h.match(/^\S+/)[0];/^-?[\d.]+m?s/.test(l)&&(l=h.match(/\S+$/)[0]);f.add(l)});return V(a,d,f,c,"@keyframes ")}function Z(a){return a.trim().replace(/'|"/gm,"").split(Y)}
function ca(a,b,c){var d=/@font-face[^}]+\}+/gm;let e,g=[];for(;null!==(e=d.exec(a));)g.push([e.index,e[0].length]);for(var f=/font-family:([^;!}]+)/,h,l=0;null!==(e=d.exec(b));)h=f.exec(e[0]),g[l++].push(Z(h[1])[0]);let k=new Set;for(h=/@font-face[^}]+\}+|font-family:([^;!}]+)/gm;null!==(e=h.exec(b));)"@"!==e[0][0]&&Z(e[1]).forEach(m=>k.add(m));d=/font:([^;!}]+)/gm;for(f=/\s*(?:['"][\w- ]+['"]|[\w-]+)\s*(?:,|$)/gm;null!==(e=d.exec(b));){for(l="";null!==(h=f.exec(e[1]));)l+=h[0];Z(l).forEach(m=>k.add(m))}return V(a,
g,k,c,"@font-face ")}function da(a){let b=a;do a=b,b=a.replace(W,(c,d,e)=>-1!=a.indexOf("var("+e+")")?c:d);while(b!=a);return b}function ea(a,b){let c=aa(a).replace(W,(d,e)=>e);a=ba(a,c,b);a=ca(a,c,b);a=da(a);return a.replace(/[^{}]+\{\s*\}/gm,"")};const fa=/\[([\w-]+)(?:(.?=)"?([^\]]*?)"?)?\]/i,ha=/:(?:first|last|nth|only|not)\b/;function ia(a){return a.replace(/:?:[a-z-]+/gm,b=>b.startsWith("::")||!ha.test(b)?"":b).replace(/:[a-z-]+\(\)/gm,"")}const ja=()=>!0;module.exports={_dropcss:function(a){const {html:b,shouldDrop:c=ja,css:d}=a,e=D(b);a=M(d);const g={};for(var f=0;f<a.length;f++){if(3!==a[f])continue;let l=a[f+1],k=l[l.length-1];f++;for(let m=0;m<k.length;m++){let H=k[m];a:for(let A=0;A<H.length;A++){let n=H[A];var h=!1;if(""!=n){if(n in g)h=g[n];else switch(n[0]){case "#":h=n.substr(1);g[n]=h=e.h.has("[id="+h+"]");break;case ".":h=n.substr(1);g[n]=h=e.B.has(h);break;case "[":if(n.startsWith("[type="))g[n]=h=e.h.has(n);else{let B=n.match(fa);g[n]=
h=e.i.some(ka=>R(ka,B[1],B[3],B[2]))}break;default:g[n]=h=e.tag.has(n)}if(!h){!0===c(l[m])?l[m]=null:g[l[m]]=!0;break a}}}}}for(f=0;f<a.length;f++)3===a[f]&&(f++,a[f]=a[f].filter(l=>{if("string"==typeof l){if(l in g)return g[l];let k=ia(l);return""==k?!0:k in g?g[k]:g[k]=U(e.i,Array.isArray(k)?k:P(k))||!0!==c(l)}return!1}));f=new Set;a=N(a,f);a=ea(a,c);return{css:a.replace(/@[a-z-]+[^{]+\{\s*\}/gm,""),sels:f}}};

//# sourceMappingURL=dropcss.js.map